# Generated by Django 5.2.17 on 2026-08-11 04:15

import api.ai.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICatalogueUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(upload_to=api.ai.models.ai_catalogue_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("total_pages", models.PositiveIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_catalogue_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AIExtractionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "page_mode",
                    models.CharField(
                        choices=[
                            ("full", "Full PDF"),
                            ("first_n", "First N pages"),
                            ("range", "Selected page range"),
                        ],
                        max_length=16,
                    ),
                ),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("page_range", models.CharField(blank=True, max_length=128)),
                ("pages_requested", models.JSONField(blank=True, default=list)),
                (
                    "model_tier",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("balanced", "Balanced"),
                            ("high_accuracy", "High accuracy"),
                        ],
                        default="high_accuracy",
                        max_length=32,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=128)),
                ("dpi", models.PositiveIntegerField(default=200)),
                ("result_json", models.JSONField(blank=True, default=dict)),
                ("pages_kept", models.PositiveIntegerField(default=0)),
                ("products_count", models.PositiveIntegerField(default=0)),
                ("advertisement_pages_skipped", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("cost_breakdown", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_extraction_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="ai.aicatalogueupload",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_extraction_runs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
