# Generated by Django 5.2.17 on 2026-08-11 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICatalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, max_length=128)),
                ("source_filename", models.CharField(db_index=True, max_length=255)),
                ("total_pages", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_catalogues_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ai.aiextractionrun",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("workspace", "source_filename")},
            },
        ),
        migrations.AddField(
            model_name="aicatalogueupload",
            name="catalogue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploads",
                to="ai.aicatalogue",
            ),
        ),
        migrations.AddField(
            model_name="aiextractionrun",
            name="catalogue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="ai.aicatalogue",
            ),
        ),
        migrations.CreateModel(
            name="AIExtractedPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_number", models.PositiveIntegerField()),
                ("page_type", models.CharField(blank=True, max_length=64)),
                (
                    "series_or_section_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("raw_text_summary", models.TextField(blank=True)),
                ("page_notes", models.TextField(blank=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "catalogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="ai.aicatalogue",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_pages",
                        to="ai.aiextractionrun",
                    ),
                ),
            ],
            options={
                "ordering": ("page_number",),
                "unique_together": {("run", "page_number")},
            },
        ),
        migrations.CreateModel(
            name="AIExtractedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_number", models.PositiveIntegerField(default=1)),
                (
                    "product_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "code_or_sku",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("price_raw", models.CharField(blank=True, max_length=64)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("description", models.TextField(blank=True)),
                ("series", models.CharField(blank=True, max_length=255)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("search_text", models.TextField(blank=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "catalogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="ai.aicatalogue",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="ai.aiextractedpage",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_products",
                        to="ai.aiextractionrun",
                    ),
                ),
            ],
            options={
                "ordering": ("page_number", "id"),
            },
        ),
    ]
