# Generated by Django 5.2.17 on 2026-08-11 07:38

import api.ai.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_aicatalogue_aicatalogueupload_catalogue_and_more"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIBusinessCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.FileField(upload_to=api.ai.models.ai_card_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("job_title", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("emails", models.JSONField(blank=True, default=list)),
                ("phones", models.JSONField(blank=True, default=list)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("address", models.TextField(blank=True)),
                ("linkedin", models.CharField(blank=True, max_length=255)),
                ("extras", models.JSONField(blank=True, default=dict)),
                ("extra_text", models.TextField(blank=True)),
                ("result_json", models.JSONField(blank=True, default=dict)),
                (
                    "model_tier",
                    models.CharField(default="high_accuracy", max_length=32),
                ),
                ("model_name", models.CharField(blank=True, max_length=128)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("cost_breakdown", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_business_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
