# Generated by Django 6.0.5 on 2026-08-17 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aibusinesscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicatalogue',
            name='business_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_business_card', to='ai.aibusinesscard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aicatalogueupload',
            name='business_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_upload_business_card', to='ai.aibusinesscard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiextractedpage',
            name='business_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_page_business_card', to='ai.aibusinesscard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiextractedproduct',
            name='business_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_product_business_card', to='ai.aibusinesscard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiextractionrun',
            name='business_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_extration_run_business_card', to='ai.aibusinesscard'),
            preserve_default=False,
        ),
    ]
