# Generated by Django 5.2.17 on 2026-08-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_aichatsession_aichatturn"),
    ]

    operations = [
        migrations.AddField(
            model_name="aibusinesscard",
            name="brands",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="aibusinesscard",
            name="source_files",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
