# Generated by Django 5.2.16 on 2026-08-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aicatalogue_business_card_and_more'),
        ('ai', '0005_aibusinesscard_brands_aibusinesscard_source_files'),
    ]

    operations = [
    ]
