# Generated by Django 5.2.17 on 2026-08-19 09:47

import api.ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_merge_20260819_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aibusinesscard",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to=api.ai.models.ai_card_upload_path
            ),
        ),
    ]
