# Generated by Django 6.0.5 on 2026-08-19 10:46

import api.ai.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_merge_20260819_1336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aibusinesscard',
            name='image',
            field=models.FileField(upload_to=api.ai.models.ai_card_upload_path),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_notes_business_card', to='ai.aibusinesscard')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ai.aicatalogue')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='catalogue_attachments/')),
                ('original_filename', models.CharField(max_length=500)),
                ('attachment_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image')], max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word'), ('powerpoint', 'PowerPoint'), ('text', 'Text'), ('csv', 'CSV'), ('other', 'Other')], max_length=20, null=True)),
                ('image_type', models.CharField(blank=True, choices=[('jpg', 'JPG'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WEBP'), ('gif', 'GIF'), ('svg', 'SVG'), ('other', 'Other')], max_length=20, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_note_attachments', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ai.note')),
            ],
            options={
                'db_table': 'note_attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['note', 'attachment_type'], name='note_attach_type_idx'), models.Index(fields=['note', 'document_type'], name='note_document_type_idx'), models.Index(fields=['note', 'image_type'], name='note_image_type_idx')],
            },
        ),
    ]
