# Generated by Django 5.2.17 on 2026-08-19 10:28

import api.ai.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0007_alter_aibusinesscard_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aibusinesscard",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to=api.ai.models.ai_card_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="aicatalogue",
            name="business_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="catalogue_business_card",
                to="ai.aibusinesscard",
            ),
        ),
        migrations.AlterField(
            model_name="aicatalogueupload",
            name="business_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="catalogue_upload_business_card",
                to="ai.aibusinesscard",
            ),
        ),
        migrations.AlterField(
            model_name="aiextractedpage",
            name="business_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="catalogue_page_business_card",
                to="ai.aibusinesscard",
            ),
        ),
        migrations.AlterField(
            model_name="aiextractedproduct",
            name="business_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="catalogue_product_business_card",
                to="ai.aibusinesscard",
            ),
        ),
        migrations.AlterField(
            model_name="aiextractionrun",
            name="business_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="catalogue_extration_run_business_card",
                to="ai.aibusinesscard",
            ),
        ),
    ]
