# Generated by Django 4.2.30 on 2026-08-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alter_aibusinesscard_image_note_aiattachment'),
        ('ai', '0008_alter_aibusinesscard_image_and_more'),
    ]

    operations = [
    ]
