# Generated by Django 5.2.17 on 2026-08-19 12:16

import api.ai.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0009_merge_20260819_1643"),
        ("suppliers", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="aicatalogue",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="aibusinesscard",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_business_cards",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="aicatalogue",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_catalogues",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="aicatalogueupload",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_catalogue_uploads",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="aiextractedpage",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_extracted_pages",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="aiextractedproduct",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_extracted_products",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="aiextractionrun",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_extraction_runs",
                to="suppliers.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="aibusinesscard",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to=api.ai.models.ai_card_upload_path
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aicatalogue",
            unique_together={("workspace", "supplier", "source_filename")},
        ),
    ]
