# Generated by Django 5.2.17 on 2026-08-20 06:18

import api.ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0010_alter_aicatalogue_unique_together_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aibusinesscard",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to=api.ai.models.ai_card_upload_path
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aicatalogue",
            unique_together={("workspace", "source_filename")},
        ),
    ]
