# Generated by Django 6.0.5 on 2026-08-20 07:33

import api.ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_alter_note_business_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aibusinesscard',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=api.ai.models.ai_card_upload_path),
        ),
    ]
